In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.ones(10)  #saving 10 ones in array x

print(x) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [5]:
y = np.zeros(10) #saving 10 ones in array y

print(y)  

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [7]:
z = np.add(x, y) #using function add in numpy to add x and y and save it in array z

print("x+y is: ", z) 

x+y is:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [9]:
#Dimension of x
dim = x.ndim
print("\nDimension of x: ", dim)

#Shape of x
shp = x.shape
print("\nShape of x: ", dim)

#Size of x
s = x.size
print("\nSize of x: ", s)

#Type of x
tp = x.dtype
print("\nShape of x: ", tp)


Dimension of x:  1

Shape of x:  1

Size of x:  10

Shape of x:  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [11]:
w = np.arange(11, 17) #create w array using arange function, values from 11 to 16

w = w.reshape(3,2) #use reshape function to change dimension to (3,2)

print(w) 

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [13]:
z = np.arange(1,4) #create z array using arange function, values from 11 to 16

print(z) 

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [15]:
newArray = np.hstack((z.reshape(3,1) , w)) #Combining two arrays horizontaly using hstack but i use reshape to change dimension of z to combine 

print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [17]:
for i in newArray:
    for j in i:
        print(j)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [19]:
newArray = newArray.T # Reverse array newArray using T

print(newArray)

[[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [21]:
newArray = newArray - 1 #Decrement newArray with 1 another option to use np.substract(newArray , 1)

print(newArray)

[[ 0  1  2]
 [10 12 14]
 [11 13 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [23]:
bgst = np.max(newArray) #Using max function to find the biggest value in newArray

print("biggest value of newArray is: " ,bgst)


sml = np.min(newArray) #Using min function to find the smallest value in newArray

print("samllest value of newArray is: " ,sml)


biggest value of newArray is:  15
samllest value of newArray is:  0


## Q#12: Print the first row of "newArray" using indexing.

In [25]:
print(newArray[0])

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [27]:
print(newArray[1 , 1]) # print element on coulmn 1 and row 1

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [29]:
print(newArray[0 , 0]) # print element on coulmn 0 and row 0

print(newArray[2 , 1]) # print element on coulmn 1 and row 2
 


0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [31]:
newArray = newArray.reshape(9,1)
print(newArray)

[[ 0]
 [ 1]
 [ 2]
 [10]
 [12]
 [14]
 [11]
 [13]
 [15]]


## Q#16: Change the shape of "newArray" to (3,2).

In [34]:
newArray = newArray.reshape(3,3) #reshape (3,2) give me error i think u mean(3,3)
print(newArray)

[[ 0  1  2]
 [10 12 14]
 [11 13 15]]


# Well Done 🎉